// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrOwSKH6wfs-W28t6_NepYPlbyshQdU8',
    appId: '1:945030521490:web:974f9afeec8715e509fc4b',
    messagingSenderId: '945030521490',
    projectId: 'mini-e-commerce-be4db',
    authDomain: 'mini-e-commerce-be4db.firebaseapp.com',
    storageBucket: 'mini-e-commerce-be4db.firebasestorage.app',
    measurementId: 'G-6YE1N0RCTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0cdcgFFBBeV_m1V7kC-InJrB0-tfhZzM',
    appId: '1:945030521490:android:477ddb928c45b95209fc4b',
    messagingSenderId: '945030521490',
    projectId: 'mini-e-commerce-be4db',
    storageBucket: 'mini-e-commerce-be4db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDhaezCezgDVLruiZvtr_dpYmKJx2dho',
    appId: '1:945030521490:ios:149a87f56951303109fc4b',
    messagingSenderId: '945030521490',
    projectId: 'mini-e-commerce-be4db',
    storageBucket: 'mini-e-commerce-be4db.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDhaezCezgDVLruiZvtr_dpYmKJx2dho',
    appId: '1:945030521490:ios:149a87f56951303109fc4b',
    messagingSenderId: '945030521490',
    projectId: 'mini-e-commerce-be4db',
    storageBucket: 'mini-e-commerce-be4db.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrOwSKH6wfs-W28t6_NepYPlbyshQdU8',
    appId: '1:945030521490:web:8b095936b26fb18c09fc4b',
    messagingSenderId: '945030521490',
    projectId: 'mini-e-commerce-be4db',
    authDomain: 'mini-e-commerce-be4db.firebaseapp.com',
    storageBucket: 'mini-e-commerce-be4db.firebasestorage.app',
    measurementId: 'G-D3CZX7K112',
  );
}
